// The directories `skills` deploys into, mirrored from its own hardcoded agent
// table (skills 1.5.13). Each is relative to $HOME and hidden (a dotdir), which
// is what makes this safe: a source repo like ~/src/hack/skills can never be one
// of these, so chopz can never mistake a source for a deploy target. That bug
// (link self-destructing a source repo) is impossible against a fixed allowlist.
//
// This is a deliberate, reviewed copy rather than the loose $HOME scan it
// replaced. Drift is fail-safe: if skills adds an agent chopz does not know yet,
// chopz simply will not discover that agent's dir for link/audit until this list
// is updated. Deployment itself still goes through `npx skills add`, which knows
// every agent, so nothing breaks, you just re-link later. To refresh:
//   npm pack skills && extract && grep the "*/skills" string literals in dist.

export const KNOWN_AGENT_SKILL_DIRS = [
  ".adal/skills",
  ".agents/skills",
  ".aider-desk/skills",
  ".astrbot/data/skills",
  ".augment/skills",
  ".autohand/skills",
  ".bob/skills",
  ".claude/skills",
  ".clawdbot/skills",
  ".cline/skills",
  ".codeartsdoer/skills",
  ".codebuddy/skills",
  ".codeium/windsurf/skills",
  ".codemaker/skills",
  ".codestudio/skills",
  ".codex/skills",
  ".commandcode/skills",
  ".config/crush/skills",
  ".continue/skills",
  ".copilot/skills",
  ".cortex/skills",
  ".crush/skills",
  ".cursor/skills",
  ".deepagents/agent/skills",
  ".devin/skills",
  ".factory/skills",
  ".firebender/skills",
  ".forge/skills",
  ".gemini/antigravity-cli/skills",
  ".gemini/antigravity/skills",
  ".gemini/skills",
  ".github/skills",
  ".goose/skills",
  ".hermes/skills",
  ".iflow/skills",
  ".inferencesh/skills",
  ".jazz/skills",
  ".junie/skills",
  ".kilocode/skills",
  ".kiro/skills",
  ".kode/skills",
  ".lingma/skills",
  ".mcpjam/skills",
  ".moltbot/skills",
  ".moxby/skills",
  ".mux/skills",
  ".neovate/skills",
  ".ona/skills",
  ".openclaw/skills",
  ".opencode/skills",
  ".openhands/skills",
  ".pi/agent/skills",
  ".pi/skills",
  ".pochi/skills",
  ".qoder-cn/skills",
  ".qoder/skills",
  ".qwen/skills",
  ".reasonix/skills",
  ".roo/skills",
  ".rovodev/skills",
  ".snowflake/cortex/skills",
  ".tabnine/agent/skills",
  ".terramind/skills",
  ".tinycloud/skills",
  ".trae-cn/skills",
  ".trae/skills",
  ".vibe/skills",
  ".well-known/skills",
  ".windsurf/skills",
  ".zencoder/skills",
];
